openapi: 3.0.0
info:
  title: Saint Seiya API
  version: 1.0.0
  description: A complete API to access detailed information about the characters from the anime Saint Seiya.

servers:
  - url: https://www.saintseiyaapi.com/api

tags:
  - name: Characters
    description: Operations related to Saint Seiya characters

paths:
  /characters:
    get:
      summary: Retrieves all characters
      description: Returns a paginated list of Saint Seiya characters.
      tags: [Characters]
      responses:
        200:
          description: Successfully retrieved the characters list.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharacterListResponse'

  /characters/{id}:
    get:
      summary: Retrieves a specific character by ID
      description: Returns the details of a Saint Seiya character.
      tags: [Characters]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the character
      responses:
        200:
          description: Character found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CharacterResponse'